### ISSUE TITLE
動きません

### ISSUE THREAD

**Issue by hiyama283** [Rabies1337/Pytive#2]
Traceback (most recent call last):
  File "C:\Users\unko\Videos\pytive-main\generate_test.py", line 107, in <module>
    generate_test()
  File "C:\Users\unko\Videos\pytive-main\generate_test.py", line 38, in generate_test
    user_id = AttrDict(json.loads(obtain_cookies.text)).user_id
  File "C:\Users\unko\Videos\pytive-main\attrdict\mixins.py", line 73, in __getattr__
    raise AttributeError(
AttributeError: 'AttrDict' instance has no attribute 'user_id'

**Comment by koaf** [comment]
ソースコードを見せてくださいますか？
